/**
 * Lead Author: Express autogenerated, Harihar
 * Main entry point for server.
 */

var express = require('express');
var path = require('path');
var bodyParser = require('body-parser');
var morgan = require('morgan');

// load configurations for mongodb and passport
var passport = require('./config/passport');
var db = require('./config/mongodb');
var logger = require('./config/logger');

// save all the model classes into a single object
var model = {
  User: require('./models/user'),
  Mapping: require("./models/mapping")
};

// load the mapping data into the database.
require("./helpers/mappings-from-file").import_mappings(path.resolve(__dirname, 'data/mapping_data.csv'),
    model.Mapping, function() {});

// create the express app that we will attach
// all our middleware to
var app = express();
app.use(bodyParser.json());
app.use(morgan('dev'));

app.use(function(req, res, next) {
  req.model = model;
  next();
});

app.use('/api/auth', require('./controllers/auth'));
app.use('/api/taste', require('./controllers/taste'));
app.use('/api/dishes', require('./controllers/recommend'));
app.use('/api/mappings', require('./controllers/mappings'));
app.use(express.static(path.join(__dirname, '../../client/build')));

module.exports = app;
